modLoader = "javafml"
loaderVersion = "[36,)"
license = "AGPL v3"
[[mods]]
modId = "plg"
version = "${file.jarVersion}"
displayName = "Permanent Light Generator"
authors = "cnlimiter, Tapio"
description = '''
Adding lightweight but effective generators for IC2 and other tech mods' appliances
'''
